### PR TITLE
Improvements on the Portuguese language translation

### PR DESCRIPTION
**Pull request by mpmont**
* Removed some comments
* Translated some elements that were still in English
* Translated some elements that were still in brazilian

### CODE REVIEW

**Comment by carlasjgomess** [comment]
As a Portuguese, I validate that this contribution is correctly written in Portuguese (Portugal).

**Comment by emersonunes** [comment]
I'm Portuguese and also a Codeigniter developer. I confirm that these translations are correct and ready to use!

**Comment by bcravo** [comment]
I'm Portuguese and also a Codeigniter developer. I confirm that these translations are correct and ready to use!

**Comment by scheillaazevedo** [comment]
I confirm the correct translation into Portuguese (Portugal)

**Pull request merged**
