### PR TITLE
Newly added language files [GREEK] (not finished)

### PR DESCRIPTION
**Pull request by harrysrevis**

### CODE REVIEW

**Comment by jim-parry** [comment]
Appreciate your contribution! Can you GPG sign commits, please? Thanks

**Comment by jim-parry** [comment]
Your title suggests the translation set isn't complete?

**Comment by jim-parry** [comment]
Looking at the translations, there are a large number that have not been translated.

**Comment by paulbalandan** [comment]
This PR seems abandoned and no signed commits. If ever you'll finish this please open a new PR with GPG-signed commits. Closing for now,

**Pull request closed without merging**
