### PR TITLE
Fix missing keys, code format, translation of TR and DE languages

### PR DESCRIPTION
**Pull request by IvanBarayev**
Translation of missing keys for DE lang
Translation of missing keys for TR lang

Code format
Added missing keys for all languages

### CODE REVIEW

**Comment by IvanBarayev** [comment]
@lonnieezell  ppl are spending time for helping, I hope, you may be more respectful, before conflicts

**Comment by lonnieezell** [comment]
@IvanBarayev I'm sorry I didn't get to these sooner. I was not aware that I wasn't getting notifications for this repo until a couple of weeks ago.

**Comment by sfadschm** [comment]
As for the German corrections here, these have mostly been handled by #79 (on 18 Feb).

**Comment by paulbalandan** [comment]
@IvanBarayev sorry your PR was not given enough attention before. Too many PRs have been merged that also dealt with your changes so I'm not sure how to proceed with yours. If there are still changes here that needs to be included in the updated language strings, please open a new PR. I'll be closing this first, as the merge conflicts are too many.

**Pull request closed without merging**
