### PR TITLE
Update Russian translation for CI4

### PR DESCRIPTION
**Pull request by DigitalWolf98**
I apologize for my past failed attempts to perform PR. The thing was that I didn't place (signingkey ?) in config git... :confused:

### CODE REVIEW

**Comment by jim-parry** [comment]
You have it sorted out now :)
The unit testing reveals two missing messages:

> 
> 25) CodeIgniter\Language\TranslationsTest::testMissingKeys with data set "ru" ('ru')
> ru is missing keys: Migrations.batchNotFound Migrations.latest Migrations.generalFault

**Comment by jim-parry** [comment]
The unit testing also reported...

> 40) CodeIgniter\Language\TranslationsTest::testExtraKeys with data set "ru" ('ru')
> ru has extra keys: Migrations.invalidType Migrations.toLatest

So, two unneeded keys and two keys missing.

**Comment by DigitalWolf98** [comment]
what keys ?. I checked two repositories CI4/translations/lang/ru/ and CI4/CI4/system/Language/en/ the differences were only in: encryption, RESTfull and email.
I kept them in storage, and I didn't even touch the rest...

**Comment by jim-parry** [comment]
system/Language/en/Migrations.php
It might have changed since you last synched.
batchNotFound is on liune 22; general Fault is on line 42
invlaidType and toLatest are not there any more

**Comment by DigitalWolf98** [comment]
Да действительно, хотя странно, что я этого не заметил. Хорошо, тогда завтра я полностью переведу все файлы, чтобы больше ничего не пропустить.

**Comment by DigitalWolf98** [comment]
Yes indeed, although strange, that I this not observed. Okay, then tomorrow I'll fully translate all the files so I don't miss anything else.

**Comment by jim-parry** [comment]
Thanks!

**Comment by DigitalWolf98** [comment]
Thank you, if it wasn't for you, I probably wouldn't have learned how to sign commits. Although I regret sending so many bad PR's. Though I'm newbie to github. :smiley:

**Pull request closed without merging**
