### PR TITLE
Swedish sv-SE translations

### PR DESCRIPTION
**Pull request by tangix**
Unsolicited Swedish translation, hopefully OK.

### CODE REVIEW

**Review by paulbalandan — CHANGES_REQUESTED** [review]
A couple of review notes:

- Please use the short format of the header license
- Make this pass Travis by commenting out those keys not yet in `framework` but are in `develop`. But do not delete those keys yet.
- Include your info in `README` and indicating the language as `Swedish - Sweden` to differentiate it with `sv-fi (Swedish - Finland)` ICU locale.

**Comment by tangix** [comment]
Updated the langauge files.

**Review by paulbalandan — CHANGES_REQUESTED** [review]
@tangix  please rebase your fork so that the new testing process is there. Also, the latest update uses the language strings in the `develop` branch of the main repo so you can uncomment those lines.

Please read on **Extending Unit Tests** in [CONTRIBUTING](https://github.com/codeigniter4/translations/blob/develop/CONTRIBUTING.md) on how to create a new test for your locale.

**Comment by paulbalandan** [comment]
OK the rebase went wrong. You can do either of these:

1. Fix the rebase by cherry picking your 5 commits into a temporary branch, delete the commits in this branch, then add those 5 commits here again, then `git push --force`.
2. OR, you can start a new PR with a fresh fork.

**Pull request closed without merging**
