### PR TITLE
Improvements on Arabic translations

### PR DESCRIPTION
**Pull request by Eyad-Mohammed-Osama**

### CODE REVIEW

**Comment by paulbalandan** [comment]
Any updates on this PR?

**Comment by Eyad-Mohammed-Osama** [comment]
> Any updates on this PR?

I can't wrap my head around those errors
I'll check it once again today

**Comment by paulbalandan** [comment]
For the build failure, it seems you have not yet translated ALL keys. You can see which are those in the error message.

For the code style, you can run `vendor/bin/php-cs-fixer fix -v` in your terminal to auto-fix them. Make sure though you have composer installed and you have run `composer update` beforehand.

**Comment by paulbalandan** [comment]
Closing for now. Please open a new PR with errors corrected already.

**Pull request closed without merging**
