### PR TITLE
New language: Latvian

### PR DESCRIPTION
**Pull request by davislasis**
Added new Latvian language translations

### CODE REVIEW

**Comment by paulbalandan** [comment]
Please rebase and GPG sign your commits.

**Comment by davislasis** [comment]
I did add GPG key to my git profile, how can add that to commit through PHPStorm?
Maybe i should make a new commit and pull request?

**Comment by paulbalandan** [comment]
I'm not familiar with phpstorm but check if there is a setting that enforces signed commits.

If not, you can do it manually.
`git commit -S -m 'Your commit message.'`

**Comment by paulbalandan** [comment]
Also, please use the short format of the header licenses to be consistent with the main repo.

**Comment by davislasis** [comment]
What is short format of the header licenses?
As Travis tests failed with missing and unnecessary keys, i guess i need to wait until CI 4.1 to come out and then push LV language in?

**Comment by paulbalandan** [comment]
> What is short format of the header licenses?
> As Travis tests failed with missing and unnecessary keys, i guess i need to wait until CI 4.1 to come out and then push LV language in?


The short format was just merged earlier. You can check that existing doc headers got changed. Also, I made a PR to change the comparison to the latest language strings in the main repo. Just waiting feedback from others.

**Comment by totoprayogo1916** [comment]
"Merging is blocked" 
remove commit un-signed

**Comment by paulbalandan** [comment]
Maybe you can squash your commits and have a single signed commit? Currently, merging is blocked once all commits are GPG signed.

Another, please add your info in the `README` and remove lv from `MISSING`.

**Comment by davislasis** [comment]
in a few hours i will be home from work, i guess most reasonable would be to delete this PR and commits and create a brand new and clean commit with PR

**Pull request closed without merging**
