### PR TITLE
[pt-br] update Portuguese translations

### PR DESCRIPTION
**Pull request by xmacaba**
Added Errors.php and Language.php files with respective translations and also completed all the missing fields listed in the translation status.

**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
You must [GPG-sign](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md) your work, certifying that you either wrote the work or otherwise have the right to pass it on to an open-source project. See [Developer's Certificate of Origin](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/DCO.md).

This is not just a "signed-off-by" commit, but instead, a digitally signed one.

See [Contribution signing](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md) for details.

**Comment by kenjis** [comment]
There are still missing translation items.
```
1) Translations\Tests\BrazilianTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "pt-BR" ('pt-BR')
Failed asserting that the language keys "HTTP.invalidJSON", "HTTP.unsupportedJSONFormat" in the main repository are included for translation in "pt-BR" locale.
Failed asserting that an array is empty.
```

**Comment by kenjis** [comment]
And coding style error.
```diff
   1) Language/pt-BR/Language.php (single_blank_line_at_eof)
      ---------- begin diff ----------
--- /home/runner/work/translations/translations/Language/pt-BR/Language.php
+++ /home/runner/work/translations/translations/Language/pt-BR/Language.php
@@ -12,4 +12,4 @@
 // "Language" language settings
 return [
     'invalidMessageFormat' => 'Formato de mensagem inválido: "{0}", Argumente: "{1}"',
-];
\ No newline at end of file
+];

      ----------- end diff -----------

   2) Language/pt-BR/HTTP.php (binary_operator_spaces)
      ---------- begin diff ----------
--- /home/runner/work/translations/translations/Language/pt-BR/HTTP.php
+++ /home/runner/work/translations/translations/Language/pt-BR/HTTP.php
@@ -58,9 +58,9 @@
     'disallowedAction' => 'A ação que você solicitou não é permitida.',
 
     // Uploaded file moving
-    'alreadyMoved' => 'O arquivo enviado já foi movido.',
-    'invalidFile'  => 'O arquivo original não é um arquivo válido.',
-    'moveFailed'   => 'Não foi possível mover o arquivo {0} para {1} ({2})',
+    'alreadyMoved'       => 'O arquivo enviado já foi movido.',
+    'invalidFile'        => 'O arquivo original não é um arquivo válido.',
+    'moveFailed'         => 'Não foi possível mover o arquivo {0} para {1} ({2})',
     'uploadErrOk'        => 'O upload do arquivo foi realizado com sucesso.',
     'uploadErrIniSize'   => 'O arquivo "%s" excede a diretiva ini upload_max_filesize.',
     'uploadErrFormSize'  => 'O arquivo "%s" excede o limite de upload definido em seu formulário.',

      ----------- end diff -----------
```

**Comment by kenjis** [comment]
Run the following command to check and fix the coding style:
```
$ bin/test pt-BR
```

**Comment by paulbalandan** [comment]
@xmacaba are you still willing to finish this PR?

**Comment by xmacaba** [comment]
> @xmacaba are you still willing to finish this PR?

yes, I'm working on it right now.. First timer.. hehe

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
