### PR TITLE
[pt] Created Portuguese (Portugal) Errors Translation

### PR DESCRIPTION
**Pull request by Nerexbcd**
**Description**
Created the Errors Translation, due to the need of it in a project currently working on.

**Checklist:**
- [X] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending PR!

Can you update missing items?
```
There were 2 failures:

1) Translations\Tests\PortugueseTranslationTest::testAllConfiguredLanguageFilesAreTranslated with data set "pt" ('pt')
Failed asserting that language files "Cookie.php", "Fabricator.php", "Language.php", "Publisher.php", "Security.php", "Test.php" in the main repository are translated in "pt" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:111
phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:106

2) Translations\Tests\PortugueseTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "pt" ('pt')
Failed asserting that the language keys "CLI.altCommandPlural", "CLI.altCommandSingular", "CLI.generator.cancelOperation", "CLI.generator.className.cell", "CLI.generator.className.command", "CLI.generator.className.config", "CLI.generator.className.controller", "CLI.generator.className.default", "CLI.generator.className.entity", "CLI.generator.className.filter", "CLI.generator.className.migration", "CLI.generator.className.model", "CLI.generator.className.seeder", "CLI.generator.className.validation", "CLI.generator.commandType", "CLI.generator.databaseGroup", "CLI.generator.fileCreate", "CLI.generator.fileError", "CLI.generator.fileExist", "CLI.generator.fileOverwrite", "CLI.generator.parentClass", "CLI.generator.returnType", "CLI.generator.tableName", "CLI.generator.usingCINamespace", "CLI.generator.viewName.cell", "CLI.namespaceNotDefined", "Cast.baseCastMissing", "Cast.invalidCastMethod", "Cast.invalidTimestamp", "Core.enabledZlibOutputCompression", "Core.invalidDirectory", "Core.invalidPhpVersion", "Database.emptyPrimaryKey", "Database.methodNotAvailable", "Files.expectedDirectory", "Files.expectedFile", "Format.invalidFormatter", "Format.invalidMime", "HTTP.cannotSetBinary", "HTTP.cannotSetCache", "HTTP.cannotSetFilepath", "HTTP.cannotSetStatusCode", "HTTP.invalidJSON", "HTTP.invalidSameSiteSetting", "HTTP.localeNotSupported", "HTTP.notFoundDownloadSource", "HTTP.unsupportedJSONFormat", "Images.fileNotSupported", "Images.webpNotSupported", "Log.invalidMessageType", "Migrations.batch", "Migrations.group", "Migrations.migrated", "Migrations.nameSeeder", "Migrations.namespace", "Migrations.refreshConfirm", "Migrations.rollBackConfirm", "Router.invalidControllerName", "Router.invalidDynamicController", "Session.invalidSameSiteSetting", "Time.invalidFormat", "Validation.alpha_numeric_punct", "Validation.equals", "Validation.is_not_unique", "Validation.not_equals", "Validation.not_in_list", "Validation.string", "Validation.valid_json", "View.invalidDecoratorClass" in the main repository are included for translation in "pt" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:169
phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:106

FAILURES!
Tests: 7, Assertions: 7, Failures: 2.
All tested locales have failed!

Passed locales (0 of 1): --
Failed locales (1 of 1): pt
```
https://github.com/codeigniter4/translations/actions/runs/7894981080/job/21546605364?pr=436

**Comment by kenjis** [comment]
See also https://codeigniter4.github.io/translations/pt.html

**Comment by kenjis** [comment]
Thank you for translations! 

Can you fix the coding style? See https://github.com/codeigniter4/translations/actions/runs/7895661649/job/21548402313?pr=436
If you can use CLI, the following command will fix them:
```console
$ bin/test pt
```

**Comment by kenjis** [comment]
There are still a few missing items.

```
There were 2 failures:

1) Translations\Tests\PortugueseTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "pt" ('pt')
Failed asserting that the language keys "HTTP.invalidJSON", "HTTP.unsupportedJSONFormat" in the main repository are included for translation in "pt" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:169
phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:106

2) Translations\Tests\PortugueseTranslationTest::testAllIncludedLanguageKeysAreTranslated with data set "pt" ('pt')
Failed asserting that the translated language keys "Migrations.batch", "Migrations.namespace" in "pt" locale differ from the original keys in the main repository.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:259
phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:106

FAILURES!
Tests: 7, Assertions: 7, Failures: 2.
All tested locales have failed!

Passed locales (0 of 1): --
Failed locales (1 of 1): pt
```
https://github.com/codeigniter4/translations/actions/runs/7895661648/job/21548419728?pr=436

**Comment by Nerexbcd** [comment]
> There are still a few missing items.
> 
> ```
> There were 2 failures:
> 
> 1) Translations\Tests\PortugueseTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "pt" ('pt')
> Failed asserting that the language keys "HTTP.invalidJSON", "HTTP.unsupportedJSONFormat" in the main repository are included for translation in "pt" locale.
> Failed asserting that an array is empty.
> 
> /home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:169
> phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:106
> 
> 2) Translations\Tests\PortugueseTranslationTest::testAllIncludedLanguageKeysAreTranslated with data set "pt" ('pt')
> Failed asserting that the translated language keys "Migrations.batch", "Migrations.namespace" in "pt" locale differ from the original keys in the main repository.
> Failed asserting that an array is empty.
> 
> /home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:259
> phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:106
> 
> FAILURES!
> Tests: 7, Assertions: 7, Failures: 2.
> All tested locales have failed!
> 
> Passed locales (0 of 1): --
> Failed locales (1 of 1): pt
> ```
> 
> https://github.com/codeigniter4/translations/actions/runs/7895661648/job/21548419728?pr=436

Those language keys are not on the original English language pack nor are marked on the translation status web page.

**Comment by kenjis** [comment]
If a translation is exactly the same as the English value, please add in `$excludedLocaleKeyTranslations` in your lang test case.
See https://github.com/codeigniter4/translations/blob/develop/tests/Language/FrenchTranslationTest.php for reference.

**Comment by kenjis** [comment]
> Those language keys are not on the original English language pack nor are marked on the translation status web page.

See https://github.com/codeigniter4/CodeIgniter4/blob/7d50bd33056cd54aef7f1905c1304947409ef078/system/Language/en/HTTP.php#L22-L23

**Review by kenjis — APPROVED** [review]
Thank you! LGTM!

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
