### PR TITLE
Added missing it translations plus some fixes on previous ones.

### PR DESCRIPTION
**Pull request by lucagrandicelli**
EOL are fixed now.

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
@lucagrandicelli can you also supply the missing keys?

**Comment by paulbalandan** [comment]
Also, please rebase so that we can have the fixed tests running on this.

**Comment by lucagrandicelli** [comment]
Well, i tried to do a rebase from origin/upstream but there are some conflicts on other languages such as pr/BR and 'ar' on Validation.php - Dunno if i better drop this fork and repull.
P.S: sorry, my GIT powers aren't still at master level :/

**Comment by sfadschm** [comment]
Sometimes starting clear really is the best option :)
Last time I had this situation, I used `git reset HEAD^` until all my own commits were removed. The changes from my commits are then marked as staged change. Then pulled the upstream and committed all staged changes together. I'm not sure if this will be trouble-free in any configuration though ... In the end, just be sure to have all your changes backed-up somewhere :)

**Comment by paulbalandan** [comment]
My git level either is not yet master level, but here is how I do it with my fork. Assuming `origin` is the remote of my fork and `upstream` is the remote of this repo.

```
git checkout develop
git pull upstream develop
git push origin develop
git checkout add_missing_it_translations
git rebase develop
# Fix any merge conflicts, then use git rebase --continue
# Since I used rebase, the GPG signature is gone so I re-sign it
git commit --amend -S
git push --force
```

**Comment by sfadschm** [comment]
> My git level either is not yet master level, but here is how I do it with my fork. Assuming `origin` is the remote of my fork and `upstream` is the remote of this repo.
> 
> ```
> git checkout develop
> git pull upstream develop
> git push origin develop
> git checkout add_missing_it_translations
> git rebase develop
> # Fix any merge conflicts, then use git rebase --continue
> # Since I used rebase, the GPG signature is gone so I re-sign it
> git commit --amend -S
> git push --force
> ```

I think this is the way it is supposed to be done by Git :-)

**Comment by sfadschm** [comment]
Great. Can you add the new `Security.php` also? Just two messages to copy from `HTTP.php`.

**Comment by lucagrandicelli** [comment]
Ok, sorry guys but i missed the new keys which i had to grab from the system/languages. Should be ok now.

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
