### PR TITLE
Updated copyright info across all languages

### PR DESCRIPTION
**Pull request by mpmont**
So you guys don't have to approve this to every language I made a pr with all the languages.

### CODE REVIEW

**Comment by lonnieezell** [comment]
thanks for this, but this should probably be addressed differently.  BCIT had it from 2014-2019. Let's do this like in the main repo, please: 

```
 * Copyright (c) 2014-2019 British Columbia Institute of Technology
 * Copyright (c) 2019-2020 CodeIgniter Foundation
```

**Comment by sba** [comment]
and how about the since-tag?
`@since      Version 4.0.0` 
for all files?

**Comment by mpmont** [comment]
ok, i'll check out how it is done in the main repo and copy the same exact structure here.

**Comment by mpmont** [comment]
This took me a bit longer than I thought. A lot of files still had copyright info from codeigniter 3. Others didn't had the same config at all. So it was not something a simple find and replace could solve. Also I had to make sure the @author tag was preserved. 

I did the best I could I think I didn't miss anything.

**Comment by sba** [comment]
thanks @mpmont, now it looks uniform across all languages!

@lonnieezell what do you think is the best procedure to add the missing keys across all languages? adding the missing key/value pairs in english to all the files to make it easier to the lindividual language maintainers to translate?

**Comment by mpmont** [comment]
Yeah while I was doing this I noticed some languages have files with missing keys. I could add them (in English) in the places they're missing. But that might be a subject for another pull request.

**Comment by sba** [comment]
yes, that needs to go in another pull request.
Travis / phpunittest lists all missing keys:
[https://travis-ci.org/github/codeigniter4/translations/jobs/691792705](https://travis-ci.org/github/codeigniter4/translations/jobs/691792705)

**Comment by mpmont** [comment]
Cool that helps a lot. I'll get on that once this one gets in.

**Comment by lonnieezell** [comment]
Yes, I think adding them in English makes sense. This is a huge one. Thanks so much!

**Comment by sba** [comment]
@mpmont did you start adding the missing strings across all languages? I could also make some language file sets..

**Comment by mpmont** [comment]
@sba Yes. Later this week I'll do a merge request with the ones I have done and we can divide them so we aren't doing the same ones.

**Comment by sba** [comment]
@mpmont can you commit the files you made? or let me know which languages I can start with?

**Comment by mpmont** [comment]
Hey mate,

I've been out for the last 2 week on travels and I'll be home this weekend.
From the top of my head I know I started with some Latin languages like
Portuguese, Brazilian, Spanish stuff like that.

I'll try and commit that this weekend when I get home.

**Comment by sba** [comment]
no problem, I don't want to stress you - then I will wait until you have commited the files you did.

**Pull request merged**
