### PR TITLE
IT: update 7 files create 3 file

### PR DESCRIPTION
**Pull request by danilort**
Update the translation for 10 files

### CODE REVIEW

**Comment by danilort** [comment]
SEE: Update Time.php for IT #261

**Comment by kenjis** [comment]
Thank you!

It seems there are coding style violations. Can you fix?
```
   1) translations/Language/it/Cast.php (single_blank_line_at_eof)
   2) translations/Language/it/Core.php (no_trailing_whitespace)
   3) translations/Language/it/Files.php (no_trailing_whitespace, no_whitespace_before_comma_in_array)
   4) translations/Language/it/Log.php (no_trailing_whitespace)
```

**Comment by danilort** [comment]
I'm sorry, can you try again?

**Review by kenjis — APPROVED** [review]
Thank you!
All checks have passed.

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
