### PR TITLE
Auto-review updating of license year

### PR DESCRIPTION
**Pull request by paulbalandan**

### CODE REVIEW

**Review by MGatner — COMMENTED** [review]
Very fancy! I haven't run this to confirm it works - do you have any example runs, like on a fork?

**Comment by paulbalandan** [comment]
Thanks! It's now working at https://github.com/paulbalandan/translations/actions/runs/3822933678/jobs/6503620710 but cannot create a PR right now because of API rate limit reached.

**Comment by MGatner** [comment]
Looks like it is working! https://github.com/paulbalandan/translations/pull/1

Awesome. Very cool project.

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
FYI: https://github.com/FantasticFiasco/action-update-license-year

**Pull request merged**
