### PR TITLE
Update Russian translate

### PR DESCRIPTION
**Pull request by DigitalWolf98**
Translations completely rewritten from **"CI4/CI4/system/Language/en"** repository.

### CODE REVIEW

**Comment by DigitalWolf98** [comment]
I assume that the error in "https://travis-ci.org/" and he can't do the test...
The thing is, I did all the translations from the beginning, comparing each line.

**Comment by DigitalWolf98** [comment]
I'm sorry, but I can't spend that much time just translating anymore. I am very sorry that they were not accepted, I will leave my fork repository open for a few days maybe you manually add it yourself.

**Comment by jim-parry** [comment]
The travis-ci errors are not for "ru" - you are good to go :)
Thank you for handling this!

**Comment by DigitalWolf98** [comment]
It seems that I was curious, if not a secret what was the reason of this error ?

**Comment by jim-parry** [comment]
The unit testing checks *all* the translation sets, and reports all of the key problems with them.
This wasn't in place until recently. It is intended to highlight omissions, so they can be fixed over time. I will add a note to the readme clarifying its use for contributors!

**Pull request merged**
