### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by grisinformatica**
Hope I made it correctly this time. Greetings

### CODE REVIEW

**Comment by paulbalandan** [comment]
Thanks for this. It seems though there are still untranslated files and keys. You can find those in the build failure.

**Comment by paulbalandan** [comment]
Almost there! Just a few more changes and we're done.

1. Some keys in HTTP, Security, and Session are not yet included for translation.
2. Your included keys in Migration contains some still in English.
3. For the code style failures, you can run `vendor/bin/php-cs-fixer fix -v` in your terminal to automatically fix those errors.

**Comment by grisinformatica** [comment]
> 3. For the code style failures, you can run `vendor/bin/php-cs-fixer fix -v` in your terminal to automatically fix those errors.

Thanks Paul. I get this error:
`PHP Fatal error:  Uncaught Error: Class 'Nexus\CsConfig\Factory' not found in /home/user/www/translations/.php-cs-fixer.dist.php:32`

**Comment by paulbalandan** [comment]
Try running `composer update` first

**Comment by grisinformatica** [comment]
Think you made it! Need to learn many things yet. Thanks for your patience

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thank you, @grisinformatica

**Pull request merged**
