### PR TITLE
Update Time.php for IT

### PR DESCRIPTION
**Pull request by danilort**

### CODE REVIEW

**Comment by danilort** [comment]
SEE: https://github.com/codeigniter4/translations/issues/260

**Comment by kenjis** [comment]
Thank you for sending PR.

It seems there are missing files and keys.

> 1) Translations\Tests\ItalianTranslationTest::testAllConfiguredLanguageFilesAreTranslated with data set "it" ('it')
Failed asserting that language files "Cookie.php", "Publisher.php", "Test.php" in the main repository are translated in "it" locale.

> 2) Translations\Tests\ItalianTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "it" ('it')
Failed asserting that the language keys "CLI.generator", "Cast.baseCastMissing", "Cast.invalidCastMethod", "Cast.invalidTimestamp", "Core.invalidPhpVersion", "Files.expectedDirectory", "Files.expectedFile", "Log.invalidMessageType", "Time.invalidFormat" in the main repository are included for translation in "it" locale.

> 3) Translations\Tests\ItalianTranslationTest::testAllIncludedLanguageKeysAreConfigured with data set "it" ('it')
Failed asserting that the translated language keys "CLI.generateClassName", "CLI.generateFileError", "CLI.generateFileExists", "CLI.generateFileSuccess", "CLI.generateParentClass" in "it" locale are configured in the main repository.


You can check any time on your local:
```
$ bin/test it
```

**Comment by danilort** [comment]
I'm sorry, but I've never made a Pull Request.
I simply made a repository fork and modified the Time.php.

I tested it on my PC (without using GIT):
```
echo "<br>EN: " . lang('Time.years', [1], 'en');				
echo "<br>EN: " . lang('Time.years', [9], 'en');				
echo "<br>IT: " . lang('Time.years', [1], 'it');				
echo "<br>IT: " . lang('Time.years', [9], 'it');				
```

OUTPUT:
```
EN: 1 year
EN: 9 years
IT: 1 anno
IT: 9 anni	
```

**Comment by kenjis** [comment]
@danilort 
Do you use Git and Composer?

**Comment by danilort** [comment]
I don't use git.
I do not use Composer (manual installation).

**Comment by kenjis** [comment]
The following files are missing or have untranslated items:
Cookie.php
Publisher.php
Test.php
CLI.php
Cast.php
Core.php
Files.php
Log.php

**Comment by danilort** [comment]
Maybe yes, but not now.

**Comment by danilort** [comment]
CLOSED.
I created a new PR: 
IT: update 7 files create 3 file #264

**Pull request closed without merging**
