### PR TITLE
[sr] Serbian Language translation

### PR DESCRIPTION
**Pull request by nebojsajsimic**
Hi i just create Serbian language translation

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending PR!

1. Please sign your commits. See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing
2. The folder should be `sr`, not `rs`.
3. Add test code for sr.
4. Update `MISSING.md` and `README.md`.

See #363 for reference.

**Comment by nebojsajsimic** [comment]
> Thank you for sending PR!
> 
> 1. Please sign your commits. See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing
> 2. The folder should be `sr`, not `rs`.
> 3. Add test code for sr.
> 4. Update `MISSING.md` and `README.md`.
> 
> See #363 for reference.

I think that everything is now fixed :)
Cheers!

**Comment by kenjis** [comment]
Thank you for updates.

Please fix the coding style.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style

**Comment by kenjis** [comment]
When you [set default signing](https://help.github.com/articles/signing-commits-using-gpg/),
if you update your branch with `git rebase`, all commits will be signed.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

**Comment by kenjis** [comment]
@nebojsajsimic We do not use `git merge` for PRs.
Please use `git rebase`.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

**Comment by kenjis** [comment]
ru's coding style is broken now. It is not your fault.
See #374

**Pull request closed without merging**
