### PR TITLE
Adding missing translations for it locale

### PR DESCRIPTION
**Pull request by lucagrandicelli**
Added missing translations for the italian language, plus some fix on the previous entries.

### CODE REVIEW

**Review by paulbalandan — COMMENTED** [review]
What happened with the header licenses? There is visibly no changes but there are diffs there. Perhaps the encoding is changed?

**Comment by sfadschm** [comment]
> 
> 
> What happened with the header licenses? There is visibly no changes but there are diffs there. Perhaps the encoding is changed?

I had this also when trying to remove the `Migrations.writeError` and such with the `it` and `es` locales.
For me, this only happened when using `Notepad2 `editor. When editing the files wih `Atom`, this did not happen.
As it didn't happen with all the other 22 locales, I come to think that the `it` and `es` locales may be encoded differently.

**Comment by lucagrandicelli** [comment]
There's a problem with the End of Line. Apparently, only on some files, when saving with LF or CRLF, the licence headers get modified as well. I'm gonna close this for now.

**Comment by paulbalandan** [comment]
@lucagrandicelli I updated the line endings to LF in #171 . I'll merge that first and you can update the it locale.

**Comment by lucagrandicelli** [comment]
> 
> 
> @lucagrandicelli I updated the line endings to LF in #171 . I'll merge that first and you can update the it locale.

Alright, Thnx.

**Pull request closed without merging**
