### PR TITLE
Updated sv-SE

### PR DESCRIPTION
**Pull request by tangix**
**Description**
Added missing Language.php and updated HTTP.php with missing JSON related strings.

**Checklist:**
- [X] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [X] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Please fix the coding style.
https://github.com/codeigniter4/translations/actions/runs/7271919525/job/19813200240?pr=424

**Comment by kenjis** [comment]
It seems your PR branch is out of dated. So the build check failed because of "lt" locale.
https://github.com/codeigniter4/translations/actions/runs/7272401137/job/19814928807?pr=424

Can you update your PR branch?
```
$ git rebase upstream/develop
```

**Comment by tangix** [comment]
> It seems your PR branch is out of dated. So the build check failed because of "lt" locale. https://github.com/codeigniter4/translations/actions/runs/7272401137/job/19814928807?pr=424
> 
> Can you update your PR branch?
> 
> ```
> $ git rebase upstream/develop
> ```

OK, will try to but clearly above my pay-grade when it comes to git knowledge...

**Comment by tangix** [comment]
Don't know how that went. Feel free to close the PR if too much problems and I will re-fork the entire repo

**Comment by kenjis** [comment]
Sorry, now this PR has many unrelated "lt" changes.
https://github.com/codeigniter4/translations/pull/424/files
Could you recreate PR?

**Comment by tangix** [comment]
Closing this and re-branching from develop

**Pull request closed without merging**
