### PR TITLE
Updated italian translation files

### PR DESCRIPTION
**Pull request by Vizzielli**
Translated missed (eng) strings, updated first comment area using last 2020 strings.

### CODE REVIEW

**Comment by lonnieezell** [comment]
@luk3b8 Do you concur?

**Comment by luk3b8** [comment]
> @luk3b8 Do you concur?

Not for all the changes. Some are good but some other not.
If I have time to check them, I'll try to suggest new translations, in a few days.

**Comment by paulbalandan** [comment]
Both maintainer and contributor have no activity for the past months and there has been no consensus on this one. As this resulted now to a large merge conflict, I'm closing it for now. Please open a new PR if there will be improvements.

**Comment by Vizzielli** [comment]
About alerts I don't know why it comes. about translation i'm sure it was better/updated than the one i used at start. In any case I suggest to choose more member for each country or if someone leave this there's no chance to receive feedback..

**Pull request closed without merging**
