### PR TITLE
[de] Update HTTP.php

### PR DESCRIPTION
**Pull request by sba**
Regarding:
https://github.com/codeigniter4/CodeIgniter4/pull/7370

### CODE REVIEW

**Comment by paulbalandan** [comment]
@sba There are new errors:
```
There were 2 failures:

1) Translations\Tests\GermanTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "de" ('de')
Failed asserting that the language keys "CLI.generator.className.cell", "CLI.generator.fileExist", "CLI.generator.viewName.cell", "Core.invalidDirectory" in the main repository are included for translation in "de" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:168
phpvfscomposer:///home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:106

2) Translations\Tests\GermanTranslationTest::testAllIncludedLanguageKeysAreConfigured with data set "de" ('de')
Failed asserting that the translated language key "CLI.generator.fileExists" in "de" locale is configured in the main repository.
Failed asserting that an array is empty.
```

**Comment by sba** [comment]
I have updated the faling language file:
https://github.com/codeigniter4/translations/pull/393

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
Errors are unrelated to the change, which we want. @paulbalandan last call

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thanks, @sba

**Pull request merged**
