### PR TITLE
[pt-BR] Update Validation

### PR DESCRIPTION
**Pull request by xgrind**
Improvement in some translations.

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you! But now GitHub Action checks fail due to  a bug in CI4 and outdated PHP versions in the workflow files.
Please wait.

**Comment by kenjis** [comment]
Now the develop branch is green.
Can you rebase (or merge develop) to update this branch?

**Comment by kenjis** [comment]
There are two missing translations. Please add.

1) Translations\Tests\BrazilianTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "pt-BR" ('pt-BR')
Failed asserting that the language keys "CLI.generator.className.test", "Validation.field_exists" in the main repository are included for translation in "pt-BR" locale.
Failed asserting that an array is empty.

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
Mnnn, I rebased from this GitHub page, but the (first) commit is not signed...
So I cannot merge this PR.

@xgrind Could you sign?

Screenshot 2024-04-15 8 47 39

**Comment by xgrind** [comment]
Signed

**Comment by xgrind** [comment]
More improvements and all signed.

**Comment by xgrind** [comment]
'Validation.php' still has an error?

**Comment by datamweb** [comment]
No, but not all of your commits are signed.

**Review by xgrind — COMMENTED** [review]
Reviewed

**Pull request closed without merging**
