### PR TITLE
Missing keys

### PR DESCRIPTION
**Pull request by mpmont**
@sba Hey mate, here's what I've done so far. I already translated the new keys added to the Portuguese Language.

Also since I'm opening these files I'm also fixings some issues like some keys are using spaces instead of tabs.

### CODE REVIEW

**Comment by sba** [comment]
@lonnieezell can you - or somebody else with write-permissions - merge the relevant open pull requests please? ..or close useless PRs. Then I will begin to add the missing keys across all language files and unify codestyle / doc-block for all files. I am afraid that otherwise a lot of merge conflicts will occur..

**Comment by paulbalandan** [comment]
@mpmont @sba what's the status of this PR? I'm starting to prune this repo in preparation for the 4.1 release in the main repo and I don't know what to do with the other PRs remaining.

**Comment by sba** [comment]
@paulbalandan as far as I have seen, the keys are now added with a different PR - but in this PR, @mpmont has translated the strings in the Portuguese files...

**Comment by mpmont** [comment]
Yes I updated some translations but I can solve the merge conflits in a new commit so that the translations can go in. I'll do that tonight.

**Comment by paulbalandan** [comment]
@mpmont Can you squash your commits and GPG sign it so that I can proceed merging it?

**Comment by paulbalandan** [comment]
Closing as filling keys with English strings as placeholders is no longer relevant, and there had been no activity in this for about a month now.

Please open a new PR to address the other concerns, and have the commits GPG-signed.

**Pull request closed without merging**
