### PR TITLE
Update chinese language for cache,cli file

### PR DESCRIPTION
**Pull request by bangbangda**
Update chinese language for cache,cli file

### CODE REVIEW

**Comment by jim-parry** [comment]
We don't have a "zh" translation to update !?

**Comment by bangbangda** [comment]
> We don't have a "zh" translation to update !?
No Chinese translation required? 
Or. Locale Folder updated to zh_cn?
@jim-parry

**Comment by jim-parry** [comment]
No one has yet provided a "zh" translation for CodeIgniter4 (or a zh-CN one)

**Comment by bangbangda** [comment]
Ok, I updated it. 
[PR 30](https://github.com/codeigniter4/translations/pull/30)

**Pull request closed without merging**
