### PR TITLE
Some small changes to translation

### PR DESCRIPTION
**Pull request by slav123**
We are happy to fill rest of the gaps

### CODE REVIEW

**Comment by lonnieezell** [comment]
@DEVELPL do you concur?

**Comment by totoprayogo1916** [comment]
@lonnieezell @DEVELPL not active in Github since Nov 2018

**Comment by slav123** [comment]
I can take over polish translations - I'm co-author of https://github.com/codeigniter-polska - we did full polish translation of user guide for CI2 ...

**Review by paulbalandan — CHANGES_REQUESTED** [review]
Please rebase and update your name in the `README`.

**Comment by paulbalandan** [comment]
@slav123 your rebase resulted to a messy commit history. You probably forgot to add `--force` when you `git push`. You may checkout this tutorial: https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

**Comment by paulbalandan** [comment]
@slav123 probably our best action for this one is to open a new PR with a fresh fork to minimise merge conflicts and messy commit history.

**Comment by paulbalandan** [comment]
Closing this for #160

**Pull request closed without merging**
