### PR TITLE
Create ge

### PR DESCRIPTION
**Pull request by JSHar**

### CODE REVIEW

**Comment by jim-parry** [comment]
We need a complete translattion set, and perhaps a description ... what language is "ge" - I don't see it in the ISO-639-1 codes list.

**Comment by JSHar** [comment]
ka-ge, georgian language, UTF-8

**Comment by jim-parry** [comment]
If you wish to do the translations, and submit a PR, that would be good.

**Comment by JSHar** [comment]
Yes, I want to make a translation.

**Comment by jim-parry** [comment]
Closing this - you need to submit a complete PR

**Pull request closed without merging**
