### PR TITLE
[de] Create Errors.php

### PR DESCRIPTION
**Pull request by sba**
german translation file for strings added in 4.3

### CODE REVIEW

**Comment by kenjis** [comment]
@paulbalandan https://github.com/codeigniter4/CodeIgniter4/pull/6288 is merged into `4.3` branch.
So the new lang file does not exist in `develop` branch.

What do we do?

**Comment by paulbalandan** [comment]
The tests were designed to test against `develop` only. So, I guess hold this off until `4.3` gets merged to `develop`?

**Comment by kenjis** [comment]
I see. I'm not sure but it might be a good way.

**Review by MGatner — APPROVED** [review]
> Hoppla!

😂

**Comment by kenjis** [comment]
> 1) Translations\Tests\GermanTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "de" ('de')
Failed asserting that the language key "HTTP.localeNotSupported" in the main repository is included for translation in "de" locale.
Failed asserting that an array is empty.

**Comment by paulbalandan** [comment]
@sba will you be able to address the failing tests?

**Comment by sba** [comment]
> @sba will you be able to address the failing tests?

the missing key I added, but I don't know what causes `Failed asserting that an array is empty.`

**Comment by kenjis** [comment]
@sba It is the same error with `Failed asserting that the language key "HTTP.localeNotSupported" in the main repository is included for translation in "de" locale.` It is original error message from PHPUnit.

**Review by kenjis — APPROVED** [review]

**Pull request merged**
