### PR TITLE
[All languages] Remove deprecated files according to main repo.

### PR DESCRIPTION
**Pull request by sfadschm**
This removes deprecated files in all languages according to #3950 of the main repo.

### CODE REVIEW

**Comment by sfadschm** [comment]
Also removed `Seed.php` which is deprecated, too.

**Comment by sfadschm** [comment]
Removed `Migration.badCreateName` and `Migrations.writeError`. 
This way, the only thing left to do in all languages is to translated missing keys, but they are otherwise clean.

I'm thinking whether to also remove keys which have been added to translations, but not translated (i.e. where the english message has just been copied). Opinions?

**Comment by sba** [comment]
I would leave the untranslated (english) strings, in the files. This makes it easier for someone to translate it without paying attention to code style, order etc. And the build checks do not fail.

**Comment by sfadschm** [comment]
Fine with that, too. Actually, the intention was to have the tests fail to represent the "true" translation state.

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
