### PR TITLE
[zh-CN] Update translations

### PR DESCRIPTION
**Pull request by vibbow**

### CODE REVIEW

**Comment by vibbow** [comment]
More fix on the way.

**Comment by kenjis** [comment]
There was 1 failure:

1) Translations\Tests\SimpleChineseTranslationTest::testAllIncludedLanguageKeysAreTranslated with data set "zh-CN" ('zh-CN')
Failed asserting that the translated language keys "Images.copyFailed", "Images.jpgOrPngRequired", "Images.missingFont", "Images.rotateUnsupported", "Migrations.migCreate", "Migrations.migHelpRefresh", "Migrations.migHelpRollback", "Migrations.migHelpSeed", "Migrations.migNumberError", "Migrations.nameMigration" in "zh-CN" locale differ from the original keys in the main repository.

**Comment by vibbow** [comment]
> There was 1 failure:
> 
>     1. Translations\Tests\SimpleChineseTranslationTest::testAllIncludedLanguageKeysAreTranslated with data set "zh-CN" ('zh-CN')
>        Failed asserting that the translated language keys "Images.copyFailed", "Images.jpgOrPngRequired", "Images.missingFont", "Images.rotateUnsupported", "Migrations.migCreate", "Migrations.migHelpRefresh", "Migrations.migHelpRollback", "Migrations.migHelpSeed", "Migrations.migNumberError", "Migrations.nameMigration" in "zh-CN" locale differ from the original keys in the main repository.

Because I didn't find where are they used for, so I leave them as untranslated.

**Review by kenjis — APPROVED** [review]

**Comment by paulbalandan** [comment]
@vibbow, why did you close this? It seems tests pass

**Comment by vibbow** [comment]
> @vibbow, why did you close this? It seems tests pass

Oh, I saw it already been approvied, so I closed this.

**Comment by kenjis** [comment]
@paulbalandan Why was zh-TW tests run?

There were 2 failures:

1) Translations\Tests\TraditionalChineseTranslationTest::testAllConfiguredLanguageFilesAreTranslated with data set "zh-TW" ('zh-TW')
Failed asserting that language files "Publisher.php", "Test.php" in the main repository are translated in "zh-TW" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:104
/home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:97

2) Translations\Tests\TraditionalChineseTranslationTest::testAllConfiguredLanguageKeysAreIncluded with data set "zh-TW" ('zh-TW')
Failed asserting that the language keys "Files.expectedDirectory", "Files.expectedFile" in the main repository are included for translation in "zh-TW" locale.
Failed asserting that an array is empty.

/home/runner/work/translations/translations/tests/Language/AbstractTranslationTestCase.php:162
/home/runner/work/translations/translations/vendor/phpunit/phpunit/phpunit:97

FAILURES!
Tests: 7, Assertions: 7, Failures: 2.
Some locales have failed the tests!

Passed locales (1 of 2): zh-CN
Failed locales (1 of 2): zh-TW

**Comment by kenjis** [comment]
@vibbow Approved is not merged. Close means to take down this PR.

**Comment by kenjis** [comment]
@paulbalandan 
```sh-session
$ git diff --name-only --diff-filter=ACMRTUXB origin/develop..HEAD
Language/zh-CN/CLI.php
Language/zh-CN/Cache.php
Language/zh-CN/Cast.php
Language/zh-CN/Cookie.php
Language/zh-CN/Core.php
Language/zh-CN/Database.php
Language/zh-CN/Email.php
Language/zh-CN/Encryption.php
Language/zh-CN/Fabricator.php
Language/zh-CN/Files.php
Language/zh-CN/Filters.php
Language/zh-CN/Format.php
Language/zh-CN/HTTP.php
Language/zh-CN/Images.php
Language/zh-CN/Log.php
Language/zh-CN/Migrations.php
Language/zh-CN/Number.php
Language/zh-CN/Pager.php
Language/zh-CN/Publisher.php
Language/zh-CN/RESTful.php
Language/zh-CN/Router.php
Language/zh-CN/Security.php
Language/zh-CN/Session.php
Language/zh-CN/Test.php
Language/zh-CN/Time.php
Language/zh-CN/Validation.php
Language/zh-CN/View.php
Language/zh-TW/Files.php
Language/zh-TW/Migrations.php
Language/zh-TW/Validation.php
```

**Comment by vibbow** [comment]
Emm, did I mess something up?

**Comment by kenjis** [comment]
@paulbalandan 
I got the reason. This PR branch is not sync with the latest develop.

It seems this is intended behavior.
zh-CN tests passed. So we ignore zh-TW test fails, right?

```
Passed locales (1 of 2): zh-CN
Failed locales (1 of 2): zh-TW
```

**Comment by kenjis** [comment]
@vibbow 
> Emm, did I mess something up?

No. No problem.


But If you rebase this branch, all tests would pass.
```
$ git checkout zh-CN
$ git fetch upstream
$ git rebase upstream/develop
$ git push --force-with-lease origin zh-CN
```

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thank you, @vibbow

**Pull request merged**
