### PR TITLE
[German] Update all files

### PR DESCRIPTION
**Pull request by sfadschm**
Related to #148.
All missing keys are added and outdated ones removed.

Two things to note:
1. I kept the alignement style of the current `translations` repo, as this was updated recently. The codeIgniter4 repo has a different one though.
2. Some keys are duplicate, e.g., `Session.invalidSameSiteSetting` and `HTTP.invalidSameSiteSetting`. Is it possible to reference such strings, so we don't have to maintain both?

All tests pass, but I will submit as a draft as I want to go over all strings until tomorrow. I think some are not consistent in the way variables and parameters are highlighted.

Improvements, corrections etc. welcome :)

### CODE REVIEW

**Comment by paulbalandan** [comment]
> 2. Some keys are duplicate, e.g., `Session.invalidSameSiteSetting` and `HTTP.invalidSameSiteSetting`. Is it possible to reference such strings, so we don't have to maintain both?

I'm not aware of this duplication. This should be addressed in the main repo rather.

**Comment by sfadschm** [comment]
This was in #3447 on the main repo.
Just noticed, that the messages are not exactly the same. In `Session.php` it says `'Session: ...'`, in `HTTP.php` its just `'...'` .

**Comment by sfadschm** [comment]
Corrected some error and refined some phrasing (at least I hope so...).
Some stuff that I noticed along the way, which should be addressed in the main repo maybe:

- Sometimes full sentences are used, sometimes `'.'` is ommitted.
- Variables/Parameters are enclosed in either `""`, `´´` or sometimes not at all.
- Embedded error messages are either `Error: {0}`, `Error: "{0}"`, `Error: "{0}".` or any other combination of those.
- There is two or three duplicate values, which might be nice to keep together.
- Is `Language.languageGetLineInvalidArgumentException` still used in the Framework? Couldn't find it. (Can we maybe add tests to verify if a language key is referenced anywhere in the Framework at all?)

Note:
In Migrations.php, the key 'on' was still present in the de translation after my previous commut but it does not exists in the Framework. Still all tests were successful.

**Comment by paulbalandan** [comment]
Migrations.on is still present. https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Language/en/Migrations.php

**Comment by sfadschm** [comment]
Oh right, my bad. It was just moved and I accidentially duplicated it in the first iteration. This explains passing tests.

**Comment by sfadschm** [comment]
Okay, I also found the `languageGetLineInvalidArgumentException` in the language tests:

https://github.com/codeigniter4/CodeIgniter4/blob/981383d56a5e93d8c7170fb668701e37ae1db09a/tests/system/Language/LanguageTest.php#L129-L136

This is only used for testing and the translation for asserting is taken from `_tests/support`, so I think we can maybe purge the `Language.php` file completely and just use any other string for testing that will always be present in the upcoming framework versions?

**Comment by paulbalandan** [comment]
Please open an issue in the main repo. For me, the english Language.php should not be in a production level status since it is only used in testing.

**Comment by sba** [comment]
Looks all okay to me - thanks for correcting and refining!

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
