### PR TITLE
Fix Missing Keys with data set

### PR DESCRIPTION
**Pull request by muh-ramadhan**
Based on the Big Indonesian Dictionary (KBBI), writing alpha-numeric words do not use hyphens.

### CODE REVIEW

**Comment by jim-parry** [comment]
The Indonesian translation has a few issues - not your fault, but would you be able to address any of them? Thanks
4) CodeIgniter\Language\TranslationsTest::testMissingFiles with data set "id" ('id')
id is missing: Cast.php RESTful.php Redirect.php Entity.php Encryption.php
16) CodeIgniter\Language\TranslationsTest::testMissingKeys with data set "id" ('id')
id is missing keys: CLI.commandNotFound Images.unsupportedImageCreate HTTP.cannotSetBinary HTTP.cannotSetFilepath HTTP.notFoundDownloadSource HTTP.cannotSetCache HTTP.cannotSetStatusCode HTTP.uploadErrOk HTTP.uploadErrIniSize HTTP.uploadErrFormSize HTTP.uploadErrPartial HTTP.uploadErrNoFile HTTP.uploadErrCantWrite HTTP.uploadErrNoTmpDir HTTP.uploadErrExtension HTTP.uploadErrUnknown Migrations.batchNotFound Migrations.migNumberError Migrations.latest Migrations.generalFault Cache.unableToWrite Database.failGetFieldData Database.failGetIndexData Database.failGetForeignKeyData Database.parseStringFail Database.featureUnavailable Database.tableNotFound Database.noPrimaryKey Database.noDateFormat Database.fieldNotExists Database.forEmptyInputGiven Database.forFindColumnHaveMultipleColumns Validation.equals Validation.not_equals
28) CodeIgniter\Language\TranslationsTest::testExtraKeys with data set "id" ('id')
id has extra keys: Files.invalidFilename Files.cannotCopy Images.unsupportedImagecreate Migrations.invalidType Migrations.toLatest

**Comment by muh-ramadhan** [comment]
> 
> 
> The Indonesian translation has a few issues - not your fault, but would you be able to address any of them? Thanks
> 4) CodeIgniter\Language\TranslationsTest::testMissingFiles with data set "id" ('id')
> id is missing: Cast.php RESTful.php Redirect.php Entity.php Encryption.php
> 16) CodeIgniter\Language\TranslationsTest::testMissingKeys with data set "id" ('id')
> id is missing keys: CLI.commandNotFound Images.unsupportedImageCreate HTTP.cannotSetBinary HTTP.cannotSetFilepath HTTP.notFoundDownloadSource HTTP.cannotSetCache HTTP.cannotSetStatusCode HTTP.uploadErrOk HTTP.uploadErrIniSize HTTP.uploadErrFormSize HTTP.uploadErrPartial HTTP.uploadErrNoFile HTTP.uploadErrCantWrite HTTP.uploadErrNoTmpDir HTTP.uploadErrExtension HTTP.uploadErrUnknown Migrations.batchNotFound Migrations.migNumberError Migrations.latest Migrations.generalFault Cache.unableToWrite Database.failGetFieldData Database.failGetIndexData Database.failGetForeignKeyData Database.parseStringFail Database.featureUnavailable Database.tableNotFound Database.noPrimaryKey Database.noDateFormat Database.fieldNotExists Database.forEmptyInputGiven Database.forFindColumnHaveMultipleColumns Validation.equals Validation.not_equals
> 28) CodeIgniter\Language\TranslationsTest::testExtraKeys with data set "id" ('id')
> id has extra keys: Files.invalidFilename Files.cannotCopy Images.unsupportedImagecreate Migrations.invalidType Migrations.toLatest

Alright I will try to overcome it as soon as possible

**Comment by jim-parry** [comment]
You are going above & beyond what I hoped for, thank you!
I was just hoping you could take care of the Indonesian hiccups :)

**Comment by muh-ramadhan** [comment]
> You are going above & beyond what I hoped for, thank you!
> I was just hoping you could take care of the Indonesian hiccups :)

Thank you, sir, I will help as much as I can :)

**Comment by muh-ramadhan** [comment]
hello sir, can my pull request not be accepted?

**Comment by jim-parry** [comment]
Sorry - didn't realize you were ready. Will review :)

**Comment by jim-parry** [comment]
Thank yoi!!

**Pull request merged**
