### PR TITLE
[ko] CLI.generator.viewName.cell, CLI.generator.className.cell add

### PR DESCRIPTION
**Pull request by Terrorboy**
Adding missed messages that were not detected in test code

CleanShot 2023-01-18 at 13 17 44

### CODE REVIEW

**Comment by Terrorboy** [comment]
https://github.com/codeigniter4/translations/issues/364

**Comment by kenjis** [comment]
`CLI.generator.className.cell` is also missing.

**Comment by Terrorboy** [comment]
@kenjis thank you.

**Review by kenjis — APPROVED** [review]

**Comment by Terrorboy** [comment]
fix wrong translation

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
