### PR TITLE
Russian translation update for CI4

### PR DESCRIPTION
**Pull request by DigitalWolf98**

### CODE REVIEW

**Comment by DigitalWolf98** [comment]
What is the reason for refusal ? I already signed my commit with RSA !

**Comment by jim-parry** [comment]
The merge is blocked because the last commit you did wasn't signed :(

**Comment by jim-parry** [comment]
ps - It's not a "refusal" - the automated rules blocked it.

The unit tests also pointed out...
_40) CodeIgniter\Language\TranslationsTest::testExtraKeys with data set "ru" ('ru')
ru has extra keys: Migrations.invalidType Migrations.toLatest_

**Comment by DigitalWolf98** [comment]
This is due to the fact that I am not at all familiar with the git because
I work with him a little. I already read about ssh keys and set it up in my
account, but I still get a refusal ... today I will try to figure it out as
you advised. thanks for the answer !

чт, 26 сент. 2019 г., 4:48 Project lead, CodeIgniter <
notifications@github.com>:

**Comment by jim-parry** [comment]
The SSH key is used for login authentication, whereas the GPG key is used for digitally signing documents.
I will merge this & fix it afterwards - we appreciate the work you have done :)
When you are ready for another contribution, let me know and I can help with the GPG signing.

**Comment by jim-parry** [comment]
Ohoh - I just noticed that your PR is to the master branch and from an unknown repository :( 
I cannot merge that because it will mess up the master & develop branches. Yikes!! 
I will close this, and could you please resubmit it, but as a PR for the develop beanch from your feature branch? Thanks.

**Pull request closed without merging**
