### PR TITLE
Sv se updates

### PR DESCRIPTION
**Pull request by tangix**
I hope I got all changes.

### CODE REVIEW

**Comment by tangix** [comment]
@paulbalandan 
PHP-CS is complaining about something but I have no clue what.

**Comment by natanfelles** [comment]
Run `vendor/bin/php-cs-fixer fix` at the root of the project

**Comment by tangix** [comment]
Can't understand what is wrong but I am sure Dante missed a tenth circle in Hell for programmers using spaces instead of tabs and using them to align stuff neatly...

**Comment by tangix** [comment]
> Run `vendor/bin/php-cs-fixer fix` at the root of the project

Gotcha. Now I definitely see a use for a 10th Circle in Hell...

**Comment by tangix** [comment]
🎉

**Review by paulbalandan — APPROVED** [review]
thank you @tangix

**Pull request merged**
