### PR TITLE
Lithuanian translation update

### PR DESCRIPTION
**Pull request by dgvirtual**
Please include this Lithuanian translation update. Unit tests were passed.

### CODE REVIEW

**Comment by dgvirtual** [comment]
Mhm, the test run by github failures seem to be unrelated to my commit - a different language... Or am I wrong?

**Comment by kenjis** [comment]
Ah, it is because of the coding standard changes.

**Comment by kenjis** [comment]
Fixed #335
Please rebase.

**Comment by dgvirtual** [comment]
> Fixed #335 Please rebase.
Hi, thanks, but could you please explain how  to do it? I am not very good at git :) Using it on Linux...

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

**Pull request closed without merging**
