### PR TITLE
Update ko.

### PR DESCRIPTION
**Pull request by Terrorboy**
add `valid_json`

### CODE REVIEW

**Comment by Terrorboy** [comment]
https://github.com/codeigniter4/translations/issues/332 fix

**Comment by Terrorboy** [comment]
Why is the test failing?
@paulbalandan

**Comment by kenjis** [comment]
It is authentication error on GitHub. We don't know why happens, but happens sometime.
```
Run composer update --ansi
Loading composer repositories with package information
Error: Could not authenticate against github.com

In AuthHelper.php line 130:
                                             
  Could not authenticate against github.com  
```

**Comment by kenjis** [comment]
I re-ran failed jobs.

**Comment by Terrorboy** [comment]
@kenjis thanks for checking

**Review by paulbalandan — APPROVED** [review]

**Pull request merged**
