### PR TITLE
[ru] fix grammar errors and add missing items

### PR DESCRIPTION
**Pull request by MalkoVrinto**
fixed some grammar errors

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending updates.

But it seems there are many missing translation items.
See https://github.com/codeigniter4/translations/actions/runs/4270646474/jobs/7439409028
Can you add them?

**Review by MGatner — APPROVED** [review]
Adding the missing keys would be great, but I'm also okay with this as an in-place improvement.

**Comment by MalkoVrinto** [comment]
> Thank you for sending updates.
> 
> But it seems there are many missing translation items. See https://github.com/codeigniter4/translations/actions/runs/4270646474/jobs/7439409028 Can you add them?

With my pleasure

**Comment by kenjis** [comment]
Thank you for adding files!

These items are not translated:
> Failed asserting that the language keys "CLI.altCommandPlural", "CLI.altCommandSingular", "CLI.generator.cancelOperation", "CLI.generator.className.cell", "CLI.generator.className.command", "CLI.generator.className.config", "CLI.generator.className.controller", "CLI.generator.className.default", "CLI.generator.className.entity", "CLI.generator.className.filter", "CLI.generator.className.migration", "CLI.generator.className.model", "CLI.generator.className.seeder", "CLI.generator.className.validation", "CLI.generator.commandType", "CLI.generator.databaseGroup", "CLI.generator.fileCreate", "CLI.generator.fileError", "CLI.generator.fileExist", "CLI.generator.fileOverwrite", "CLI.generator.parentClass", "CLI.generator.returnType", "CLI.generator.tableName", "CLI.generator.usingCINamespace", "CLI.generator.viewName.cell", "CLI.namespaceNotDefined", "Cast.baseCastMissing", "Cast.invalidCastMethod", "Cast.invalidTimestamp", "Core.invalidPhpVersion", "Database.emptyPrimaryKey", "Database.methodNotAvailable", "Fabricator.createFailed", "Files.expectedDirectory", "Files.expectedFile", "Format.invalidFormatter", "Format.invalidMime", "HTTP.invalidSameSiteSetting", "HTTP.localeNotSupported", "Images.webpNotSupported", "Log.invalidMessageType", "Migrations.batch", "Migrations.group", "Migrations.migrated", "Migrations.nameSeeder", "Migrations.namespace", "Router.invalidControllerName", "Router.invalidDynamicController", "Session.invalidSameSiteSetting", "Time.invalidFormat", "Validation.not_in_list", "Validation.valid_json", "View.invalidDecoratorClass" in the main repository are included for translation in "ru" locale.
https://github.com/codeigniter4/translations/actions/runs/4305274333/jobs/7517427605

**Comment by MalkoVrinto** [comment]
> Thank you for adding files!
> 
> These items are not translated:
> 
> > Failed asserting that the language keys "CLI.altCommandPlural", "CLI.altCommandSingular", "CLI.generator.cancelOperation", "CLI.generator.className.cell", "CLI.generator.className.command", "CLI.generator.className.config", "CLI.generator.className.controller", "CLI.generator.className.default", "CLI.generator.className.entity", "CLI.generator.className.filter", "CLI.generator.className.migration", "CLI.generator.className.model", "CLI.generator.className.seeder", "CLI.generator.className.validation", "CLI.generator.commandType", "CLI.generator.databaseGroup", "CLI.generator.fileCreate", "CLI.generator.fileError", "CLI.generator.fileExist", "CLI.generator.fileOverwrite", "CLI.generator.parentClass", "CLI.generator.returnType", "CLI.generator.tableName", "CLI.generator.usingCINamespace", "CLI.generator.viewName.cell", "CLI.namespaceNotDefined", "Cast.baseCastMissing", "Cast.invalidCastMethod", "Cast.invalidTimestamp", "Core.invalidPhpVersion", "Database.emptyPrimaryKey", "Database.methodNotAvailable", "Fabricator.createFailed", "Files.expectedDirectory", "Files.expectedFile", "Format.invalidFormatter", "Format.invalidMime", "HTTP.invalidSameSiteSetting", "HTTP.localeNotSupported", "Images.webpNotSupported", "Log.invalidMessageType", "Migrations.batch", "Migrations.group", "Migrations.migrated", "Migrations.nameSeeder", "Migrations.namespace", "Router.invalidControllerName", "Router.invalidDynamicController", "Session.invalidSameSiteSetting", "Time.invalidFormat", "Validation.not_in_list", "Validation.valid_json", "View.invalidDecoratorClass" in the main repository are included for translation in "ru" locale.
> > https://github.com/codeigniter4/translations/actions/runs/4305274333/jobs/7517427605

Already translated :)

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thank you, @MalkoVrinto for your contribution!

**Comment by MalkoVrinto** [comment]
> Thank you, @MalkoVrinto for your contribution!

:handshake:

**Comment by kenjis** [comment]
It seems ru is broken now.

```
1) Translations\Tests\RussianTranslationTest::testAllConfiguredLanguageKeysAreInOrder with data set "ru" ('ru')
Failed asserting that the translated language keys in "ru" locale are ordered correctly.
--- Original
+++ Translated

Migrations.php:
-'migSeeder' => 'Seeder name';
+'on' => 'Миграция на: ';
Failed asserting that an array is empty.
```

**Comment by MalkoVrinto** [comment]
> It seems ru is broken now.
> 
> ```diff
> 1) Translations\Tests\RussianTranslationTest::testAllConfiguredLanguageKeysAreInOrder with data set "ru" ('ru')
> Failed asserting that the translated language keys in "ru" locale are ordered correctly.
> --- Original
> +++ Translated
> 
> Migrations.php:
> -'migSeeder' => 'Seeder name';
> +'on' => 'Миграция на: ';
> Failed asserting that an array is empty.
> ```
> 
> See https://github.com/codeigniter4/translations/actions/runs/4370681286/jobs/7645827066

The keys in Migrations.php are ordered correctly now.

**Comment by kenjis** [comment]
The keys in Migrations.php are not ordered correctly:
https://github.com/codeigniter4/translations/blob/5b7fc9df6c09a2840649c9165804db46839936bd/Language/ru/Migrations.php#L45-L46
https://github.com/codeigniter4/translations/blob/5b7fc9df6c09a2840649c9165804db46839936bd/Language/ja/Migrations.php#L45-L46

**Pull request merged**
